### PR TITLE
AppVeyor support/integration

### PR DESCRIPTION
**Pull request by Jeavon**
I have this building correctly on my fork so hopefully should be straight forward. (https://ci.appveyor.com/project/JeavonLeopold/umbraco-nested-content)

Three things for you to do post merge:
1. Add the package icon to the master branch of GitHub and update IconUrl in package.proj (I've currently set this to the icon on Our)
2. Uncomment and populate the deploy section of appveyor.yml adding the encrypted API keys for NuGet, MyGet & GitHub (I recommend this extension for VS https://visualstudiogallery.msdn.microsoft.com/34423c06-f756-4721-8394-bc3d23b91ca7)
3. Add the shields.io badges to your readme.md

Any questions/problems, let me know on Gitter or Skype.

### CODE REVIEW

**Comment by Jeavon** [comment]
@leekelleher any issues with this? Would love to be able to get this awesome package from NuGet :)

**Comment by leekelleher** [comment]
No issues, only that I didn't have time to test before my holiday. (It was
a manic few weeks). I'm back from holiday on the 11th.

**Comment by Jeavon** [comment]
Ah ha, enjoy the last days of your holiday!

**Comment by leekelleher** [comment]
I've finally got around to merging it in!  Thanks again @Jeavon! #h5yr

**Comment by Jeavon** [comment]
Great, look forward to switching to using from NuGet :)

**Comment by leekelleher** [comment]
I've (finally) set up the MyGet feed:
https://www.myget.org/F/umbraco-nested-content/api/v2
(I'm not sure about the "/api/v2" part on the end...?)

I've also set-up the NuGet part too... that'll kick in on the next release (tag on `master`)

**Pull request merged**
