### PR TITLE
Added ncMediaName filter for name template

### PR DESCRIPTION
**Pull request by dawoe**

### CODE REVIEW

**Comment by dawoe** [comment]
For issue #128

**Comment by leekelleher** [comment]
@mattbrailsford - moving any discussion from #128 to here. Thoughts?
No rush though; _(it's public holiday in the UK today)_

**Comment by mattbrailsford** [comment]
I get the reason, but I think just copying the content one is a bit of a code smell. What if you need one for members? or some other entity type? We are going to end up with multiple versions of the same code.

It would be much better to extend the first one to accept a "type" parameter so you can set the type of entity you are linking to (making it default to 'Document' for backwards compat). For none document nodes, it would change the syntax to:

    {{ picker | ncNodeName:'Media' }}

To accept a type param, you'll need to change [line 12](https://github.com/dawoe/umbraco-nested-content/blob/bfcea9309bf7f5310cb71d80aacfb685308ce207/src/Our.Umbraco.NestedContent/Web/UI/App_Plugins/NestedContent/Js/nestedcontent.filters.js#L12) to include another param, but then just change [line 37](https://github.com/dawoe/umbraco-nested-content/blob/bfcea9309bf7f5310cb71d80aacfb685308ce207/src/Our.Umbraco.NestedContent/Web/UI/App_Plugins/NestedContent/Js/nestedcontent.filters.js#L37) to use that param (doing an undefined/null check first so that 'Document' is used by default).

**Comment by leekelleher** [comment]
@mattbrailsford oooo, TIL that Angular filters have params. 😎

**Comment by dawoe** [comment]
Will try to update it.. just need to find some time to do it. A little bit swamped in work just before codegarden

**Comment by leekelleher** [comment]
Closing the PR, as we don't want to introduce any features that are different to the Umbraco core version.
Please feel free to raise this with the Umbraco core team via their issue tracker.

**Pull request closed without merging**
