### PR TITLE
Support multiple doctypes

### PR DESCRIPTION
**Pull request by kjac**
Make it possible to add multiple different doctypes to the item list.

**Please note** that this PR changes the data format for both the prevalues and the content editor, and it is not backwards compatible.

### CODE REVIEW

**Comment by mattbrailsford** [comment]
Few things
- If doc type doesn't have icon set, default to doctype icon in picker  
- Store in the raw value the doc type guid, not alias. This prevents loss of data if an alias is renamed.  
- We do need a better prevalue UI for choosing doctypes, as the tabs / name templates are also template specific, so we need ways of defining those for each doctype selected. Maybe something like the listview prevalue? Dropdown to choose a doctype with "Add" next to it. Clicking "Add" adds to a table showing the doc type name and next to it a dropdown for the tabs, and a field for the name template, plus another button for remove. We could have sorting aswell to allow people to set the order they appear in?

Other than that, it looks really nice.

**Comment by kjac** [comment]
I agree on points 1 and 3, but storing the doctype alias instead of its guid gives a few advances:
1. You don't have to map the doctype guid to the corresponding alias in order to fetch the doctype using the Umbraco API
2. From a deployment perspective it's more convenient to use doctype aliases.
If anything I would consider dropping the doctype guids in the prevalues too, in favor of the doctype aliases. 
And finally, renaming an alias already leads to a world of pain in Umbraco, so odds are it won't happen that much.

**Comment by mattbrailsford** [comment]
Hmm, I get your point about deployment as if you do have multiple environments, then yea, they would end up with different GUID's. It is just concerning though that if you do name it wrong, or later down the road you want to name it more meaningful to the client, you are stuffed unless you do a replace in the database.

@leekelleher what do you think? Did the use of GUID's help or hinder with courier deployments?

**Comment by kjac** [comment]
It definitively requires your deployment tool to enforce guids across environments. Not sure uSync does that.... I'm pretty sure Umport does not (yet) do that.

**Comment by leekelleher** [comment]
@mattbrailsford - Courier uses DocType aliases.

We decided to use GUIDs for Mortar to get around the renaming issue - as it is a major showstopper if that happens, (unless we hook into events to _somehow_ manipulate the JSON?)

**Comment by kjac** [comment]
@leekelleher @mattbrailsford I must admit I don't see it as a particularly big issue. It's just how Umbraco always worked: If you change a doctype alias in an Umbraco project, stuff breaks - you'll need to rewrite views, republish content, redo selections in node pickers that can select documents of this particular doctype, wrestle courier/uSync/Umport deployments and so on... bottom line, once your Umbraco project is in a near-production-ready state, you generally won't ever rename the alias of a doctype (or any other alias for that matter of fact), simply because it destabilizes the project.

It's not ideal, but I'd rather have a deployment friendly datatype at the cost of not being able to change doctype aliases, than a guard against doctype alias changes at the cost of having to manually deploy the datatype.

**Comment by mattbrailsford** [comment]
I think the issue is, yes, you have to fix your views, but that stuff is easy. If you loose your data, your are stuffed. Rename a doctype in umbraco, and your content node still knows it's doc type and remains the same. The data stays.

The issue is, using doc type alias, there is simply no way of recovering your data without playing in the database.

I dunno if hooking into events to detect a doc type alias rename will help, because if we have an NC inside a DTGE, the data is stored pretty deep, so we'd need to pattern match on the json which wouldn't be ideal.

**Comment by kjac** [comment]
Hooking into events is probably not a solution that will work for terribly long; as soon as the prevalue format changes, the event handling will have to be changed accordingly, and sooner or later this will just become too error prone.

I'd love to hear other people's view on this issue - are people deploying by hand or using tooling, and will said tooling work with doctype guid matching or alternatively allow for exempting NC datatypes during import on the target environment?

I can easily rewrite the PR to work with doctype guids, and I also have a new prevalue editor sort of ready (a bit of rewrite pending the output of this discussion). Guess all we need is a decision :)

**Comment by KevinJump** [comment]
uSync doesn't enforce the doctype guid between sites (i'm not 100% sure you can with the API - I might play about with that a bit),

For deployments then alias is always going to be nicer - because it forgives a multitude of sins, allows for times when things on either side might have been created out of sync from each other.

When deploying with IDs you need to be much more careful and methodical, because if the IDs go out of sync then you can be in trouble and end up with duplicates.

in uSync you can turn off exporting all datatypes - but not individual ones, but you could write a quick event listener for uSync that would prevent the .configs been written out for this type.

**Comment by mattbrailsford** [comment]
All IEntity's (which I believe anything based on the node table should be) should have a Key property which is the items guid so you should be able to access it / set it, but I do get what you mean about aliases being easier.

I just can't decide whether loss of data should be the biggest priority here though, even though it is a little more complex.

**Comment by KevinJump** [comment]
what happens to the datatype if someone deletes a DocType? (besides they get what they deserve!)

**Comment by mattbrailsford** [comment]
lost data I guess (which you can't get back by recreating a new doctype with the same alias)

**Comment by mattbrailsford** [comment]
So, I got to thinking this morning, if we were to go doc type aliases, what could we provide at bare minimum to allow people to fix their content if they did decide they wanted to rename their doctype. The best I could come up with would be a SQL statement to do a find and replace (it needs to be at the SQL level, as a NC raw value, could be stored within a DTGE so you can't just look for NC properties).

``` sql
DECLARE @oldAlias varchar(100)
DECLARE @newAlias varchar(100)

SET @oldAlias = 'OldDocTypeAlias'
SET @newAlias = 'NewDocTypeAlias'

UPDATE [cmsPropertyData]
SET [dataNtext] = REPLACE(REPLACE([dataNtext], '"docType": "'+ @oldAlias +'"', '"docType": "'+ @newAlias +'"'), '"docType":"'+ @oldAlias +'"', '"docType":"'+ @newAlias +'"')
WHERE [dataNtext] LIKE '%"docType":[^"]"'+ @oldAlias +'"%'

UPDATE [cmsPreviewXml]
SET [xml] = REPLACE(REPLACE([xml], '"docType": "'+ @oldAlias +'"', '"docType": "'+ @newAlias +'"'), '"docType":"'+ @oldAlias +'"', '"docType":"'+ @newAlias +'"')
WHERE [xml] LIKE '%"docType":[^"]"'+ @oldAlias +'"%'
```

This is currently just for property data, so we would potentially need another to fix the prevalue data, and then the user would have to rebuild their site lucene index etc.

The only potential flaw with this ATM is that it assumes we are the only ones storing a doctype alias in a json value matching the pattern "docType": "alias"

Comments?

**Comment by kjac** [comment]
A different approach would be to let the new and improved doctype-tabalias-nametemplate prevalue editor somehow support doctype alias changes. 

Theoretically we could find all doctypes using the NC data type in question, then find all documents based on these doctypes and update the NC property value JSON with the new doctype aliases. But it's a bit of work to be honest, and I'm not a big fan of modifying documents behind the user's back. Just thought I'd mention it as an option.

I still believe that data loss it's a perfectly valid behavior for an Umbraco data type that's based on the aliases of other Umbraco elements, when said aliases change. If I recall correctly, this behavior is even seen on the built-in content picker?

**Comment by mattbrailsford** [comment]
Maybe if we prefix our doctype alias field on our json object, it would make it easier to find / replace, ie "ncDocType": "DocTypeAlias" (we could then do the same with DTGE "dtgeDocType": "DocTypeAlias") then we know in our SQL statement we are only ever affecting our specific model?

**Comment by mattbrailsford** [comment]
PS I agree, modifying the data model should not be something we do automatically

**Comment by mattbrailsford** [comment]
Ok, so here is the decision then, lets go aliases throughout, but wherever we store an alias in a json object, make sure that that property is prefixed with "nc" to give people an easy handle to find and replace on. It shouldn't mean much for us in development, but it's a big help if you change your alias and want to fix your data.

@leekelleher is this a decision we want to take over to DTGE too?

One other thing worth looking at, is investigating whether we can implement these changes in such a way so they auto fix coming from the old data structure. It would potentially require people to resave their values, but that's better than saying you are stuffed and can't upgrade.

**Comment by leekelleher** [comment]
@mattbrailsford Yes, I think we should keep DTGE consistent with NC decisions. :+1:

**Comment by kjac** [comment]
:+1: I'll refactor a few things and update the PR in the weekend. 

With regards to migrating the previous data formats, I'll keep that out of this PR. I'm not even sure it's really possible, specially not for the prevalue editor - the list of [doctype alias, tab alias, name template] sets will replace three individual prevalues.

**Comment by mattbrailsford** [comment]
@kjac it's worth looking. If a prevalue editor has access to the entire stored prevalue config, it should be possible to look up the old properties and remap them to the new structure. I can't be sure though, but it's worth looking. 

Thanks for the work on this so far. Other than the alias dilemma, it's still awesome :)

**Comment by kjac** [comment]
@mattbrailsford @leekelleher The PR has been updated with the new prevalue editor and the "nc"-refactoring of stored aliases. I've prefixed the stored tab aliases as well for good measure.

As you can see, I've started a subtle name change throughout the code from "doctype" to "contenttype", to align the code semantics with the Umbraco code semantics. There are still a few things to be done in this regard, but that's beyond the scope of this PR - for now I've just made sure to rename the stored prevalues and values to avoid future loss of data.

**Comment by kjac** [comment]
Added converter from the current (v0.1.1) data formats for both prevalue and value editors.

**Comment by kjac** [comment]
Did a little refactoring to make sure that nodes are always created and initialized in the same way.

**Comment by mattbrailsford** [comment]
Just playing with this now and am pretty damn impressed. Nice work @kjac. Having it auto fix itself is such a worthwhile thing so good job on getting that working. And the doctype/tab/template editor works really nicely.

I think the only comment I would have now is, I like the help text you've added, but I wonder if this should be behind a help icon next to the add button? Clicking it expands to show the help text. That way it's not taking up a ton of space once you know what you are doing. What do you think?

Matt

**Comment by kjac** [comment]
Hiya. Sure I can do that, shouldn't be a problem. I was torn myself about the help text, after all it's not really the "Umbraco way" of doing things. But the editor itself is far from self explanatory, so I felt it was better to add the help text. 

I'll update the PR soon, and also add another small bugfix to ensure that the sort order of the selected doctypes is enforced in the editor.

**Comment by kjac** [comment]
There we go, added help icon and explicit sorting of the selected doctypes.

**Comment by joshua-stewart** [comment]
@kjac In Firefox the openNodeTypePicker call fails with event undefined, preventing the doctype overlay picker from popping up. I fixed this by changing it to:

$scope.openNodeTypePicker = function (event) 

and changing the ng-click to:

 openNodeTypePicker($event)

Thanks for working so diligently to improve such an awesome and useful package. I can't wait until this request is merged.

**Comment by kjac** [comment]
@joshua-stewart Thanks! I've tested your fix on Firefox and Chrome and it works in both browsers, so the PR has been updated accordingly :)

**Comment by joshua-stewart** [comment]
@kjac You're welcome. I love this package. I hope it gets rolled into the core soon, or at a minimum your pull request gets merged into the package. I have a few enhancements I'd like to contribute like adding the doctype icons to each item so you can tell visually what is what when using multiple doctypes. 

With regards to this package being added to the core, if this does get rolled into the core, how hard would it be for this functionality to live under a separate node in the settings tree called Nested Content? This would allow for a complete separation from traditional doctypes. Are there any drawbacks to doing this?

**Comment by kjac** [comment]
That would be possible, and with no real drawback unless you're planning to
use the same doctype for both regular content and nested content. However,
there's a long stretch until this package can be added to the core. I have
a few bug fixes I'll add when I have the time, and I'm sure there are lots
more. Besides, adding it to the core means a less agile rollout of updates
to the package, and not least enforcing an umbraco upgrade for the sake of
deploying new features for NC. And we all know that despite the best
efforts of the core team, and umbraco upgrade is not always just next next
finish. So there are some arguments against adding it to the core.

...but that's a whole other discussion :-)

**Comment by joshua-stewart** [comment]
Awesome. Thanks for the feedback. :-)

**Comment by kjac** [comment]
Forward merged from develop.

**Comment by tomfulton** [comment]
@kjac Hi all!  I haven't looked at the code yet and this is my first time using Nested Content, but just thought I'd let you know that I worked on a new site from Kenn's `multiple-doctypes` branch and all worked perfectly :+1:

**Comment by kgiszewski** [comment]
Any luck with nesting nested content?

**Comment by tomfulton** [comment]
@kgiszewski Hmm..hadn't tried that yet, didn't need it for this project.  Is that not supported?

**Comment by mattbrailsford** [comment]
Cheers @tomfulton for testing. We've been playing with it too and are pretty happy with it so should be in the next release.

**Comment by kgiszewski** [comment]
@tomfulton _shrugs_ :) Been holding off using this package until this branch was merged.

**Comment by kjac** [comment]
@tomfulton cool. It's been a while since I did it but I recall testing it rather intensively, so I'm glad it works for ya :)
@kgiszewski not sure nested nested content is supported. I haven't explicitly tested it, but it'll probably work (at least until validation issues pop up, huh!).

**Comment by mattbrailsford** [comment]
@kgiszewski it'll probably work, but it's not something we intend to support explicitly. Nested content's focus is really to do simple lists, so if you need lists in lists, it goes a bit beyond what the UI can probably handle.

**Comment by kgiszewski** [comment]
Ok no problem. Trying to see if most of Archetypes features have a mapping.

**Comment by kjac** [comment]
Oi! I for one don't see nested content as any kind of replacement for
archetype. Much more like a simpler supplement. The data model for nested
content (based on documents) simplifies a lot of things compared to
archetypes data structure, but at the same time it limits the possible
feature set of nested content. So don't you dare give up on archetype :-)

**Comment by kgiszewski** [comment]
Ha, well I've sort of imagined that Nested Content was the eventual successor to Archetype :)  Not killing it off anytime soon.  Perhaps it'll limp to Umbraco 8.

**Comment by mattbrailsford** [comment]
@kgiszewski  I agree with @kjac, Nested Content has no intentions to be an Archtype killer, and I totally see the need for both packages. Nested Content will be for simple content lists, nothing more (kinda like embedded content from a few years back). So if a more complex data model is required, then Archetype would definitely be a better solution in that instance.

**Comment by leekelleher** [comment]
MERGED! Thanks @kjac #h5yr

**Comment by kjac** [comment]
Lovely :) and you're very welcome!

**Pull request merged**
