### PR TITLE
Add install.ps1 

### PR DESCRIPTION
**Pull request by Jeavon**
Often when updating Umbraco NuGet packages that contain App_Plugin content we have excluded the folder from our solution so the files don't get upgraded. This install.ps1 copies the "App_Plugins/NestedContent" folder to the correct path if it's been excluded from the VS project since original installation, it it hasn't it been excluded, it does nothing

### CODE REVIEW

**Comment by mattbrailsford** [comment]
What does this do when installed in a website project? Has this scenario
been tested?

**Comment by Jeavon** [comment]
Haven't tested but I'm pretty sure it will do nothing as there is no concept of excluding folders or files so the folders will be there. I don't think I've ever installed a NuGet package in a website project, I'll give it a try and see what happens

**Comment by mattbrailsford** [comment]
my fear is the use of $project.FullName will cause an error as I think its a URL in a website project.

**Comment by Jeavon** [comment]
You were right, I have added a earlier check for the App_Plugins/NestContent folder so it works fine now. Really interesting how NuGet works with Website projects, I've never tried it before :)

**Comment by mattbrailsford** [comment]
Tell me about it, I've been trying to get core to support them for months. Created a PR to make it work and everything https://github.com/umbraco/Umbraco-CMS/pull/738

**Comment by leekelleher** [comment]
Picking up on this.  I'm cool with having this merged in.  @mattbrailsford do you have any concerns? (re: Website projects)

@Jeavon - cosmetic question, does the "Install.ps1" file need to be capitalised? Can it be lowercase? (I can do that post-merge if so)

**Comment by Jeavon** [comment]
@leekelleher I don't know if it has to be capitalised, but the NuGet docs always have it that way e.g. https://docs.nuget.org/create/creating-and-publishing-a-package#user-content-automatically-running-powershell-scripts-during-package-installation-and-removal

**Comment by leekelleher** [comment]
@Jeavon No worries, it's just me being pedantic :stuck_out_tongue_closed_eyes:

**Comment by Jeavon** [comment]
@leekelleher it's interesting, I'm always confused, MS guidelines would have it capitalised wouldn't they...?

**Comment by leekelleher** [comment]
@Jeavon Yeah, that NuGet doc mentions "Install.ps1", then in the detail it goes lowercase...

> If your package also has an init.ps1, install.ps1 runs after init.ps1.

I think it's fine either way.

**Comment by Jeavon** [comment]
@leekelleher hmmm, if they mix it up there then I guess it doesn't matter...

**Pull request merged**
