### PR TITLE
Adds Group to the PropertyEditor attribute

### PR DESCRIPTION
**Pull request by tompipe**
Add a group to the property editor attribute. This tidies the select editor dialog by grouping all nested content editors together

### CODE REVIEW

**Comment by tompipe** [comment]
Aaaah dammit, Group property wasn't added until 7.4.0 :(

**Comment by leekelleher** [comment]
Thanks @tompipe! I'm not sure what we're doing about upgrading the Umbraco dependency yet, but let's keep this PR open for now 👍

**Comment by tompipe** [comment]
Cheers. Would be good to get the dependency upgraded, but know it's time consuming to do all the testing etc. Happy to help if you need any though. :)

**Comment by tompipe** [comment]
I will not be defeated ;)

https://gist.github.com/tompipe/87e03be7572712872e6fcb0abb6e396c

**Comment by leekelleher** [comment]
Closing this PR.  NC in Umbraco core has been added to the "lists" group.

https://github.com/umbraco/Umbraco-CMS/commit/7806246a522181b6ca6bcb174f69304857a47ee5

**Pull request closed without merging**
