### PR TITLE
Add PropertyValueType attribute to help models builder #49

### PR DESCRIPTION
**Pull request by cwjackso**

### CODE REVIEW

**Comment by mattbrailsford** [comment]
Guess this means single item mode won't work properly then as our resolver can resolve multiple value types.

**Comment by leekelleher** [comment]
@zpqrtbnk Can you offer any advice on how we could handle multiple value types?

e.g. our ValueConverter could return either an `IEnumerable<IPublishedContent>` or a single `IPublishedContent`

**Comment by cwjackso** [comment]
I imagine two property value converters would be needed. However the "IsConverter" method has no context of value so it could not be done at run time.

I suppose it opens the discussion into if a single property editor should be returning two different types though. Its easy in code to .FirstOrDefault() if you know there is only going to be one. but that's a breaking change now.

**Comment by mattbrailsford** [comment]
Yea. Guess it just sucks as these are new rules that weren't a requirement
previously.

Yes we could just return enumerable, but would make the code a bit uglier.
Don't think it'll be possible to have converters for the same PE though.

**Comment by cwjackso** [comment]
@mattbrailsford it may be possible just looking at the converter actually.

the single return works on min/max item pre-values so splitting the converter in two should be possible. I have 30 mins if you want me to look at another pull request?

**Comment by mattbrailsford** [comment]
Who am I to stop you :)

**Comment by leekelleher** [comment]
@cwjackso By all means, please do :sunglasses:

**Comment by cwjackso** [comment]
Ok, that works nicely! I've pulled some logic out into static extensions but thought that would be cleaner than extending the converter?

Thanks

**Comment by mattbrailsford** [comment]
Have you tested it in non-models builder manner? ie, from within a normal view can you still do Model.GetPropertyValue< IEnumerable< IPublishedContent>>("alias") and Model.GetPropertyValue< IPublishedContent>("alias")

**Comment by leekelleher** [comment]
@mattbrailsford I think they should be okay, as `GetPropertyValue` extension method is a wrapper for `GetProperty("alias").Value.TryConvertTo<T>` (obviously that's "in a nutshell" :wink:) ... so the PVC returns the appropriate object-type and `TryConvertTo<T>` attempts to cast/convert it accordingly.

(Sorry if I'm teaching you to suck eggs :blush:)

**Comment by leekelleher** [comment]
@cwjackso Good work, we'll review as soon as we can.

**Comment by mattbrailsford** [comment]
It's cool, I'm just throwing things out there as they come to mind, not really with any backing :)

**Comment by mattbrailsford** [comment]
Nice work @cwjackso though on such a fast fix

**Comment by cwjackso** [comment]
Like a fool I only tested the model building and hadn't tested the retrieval at all. I wasn't returning the converted value in either converter!

The last commit is now tested for retrieval via both strong typed model and .GetPrpertyValue(). As @leekelleher says they are essentially the same thing though.

Thanks

**Comment by mattbrailsford** [comment]
Never hurts to double check :) Nice work fella :clap:

**Pull request merged**
